/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author João Pedro
 */
public class INConfronto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(INConfronto.class.getName());

    /**
     * Creates new form Confronto
     */
   // O "motor" que nos permite adicionar linhas na tabela
    private javax.swing.table.DefaultTableModel modeloTabela;

    public INConfronto() {
        initComponents();
        
        // Evita fechar o programa inteiro ao fechar essa janela
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Captura o modelo da tabela que você desenhou no NetBeans
        modeloTabela = (javax.swing.table.DefaultTableModel) jtabelaClassificacao.getModel();
        
        // Carrega os grupos cadastrados no ComboBox
        carregarComboGrupos();
    }
    
    private void carregarComboGrupos() {
    jcboxGrupos.removeAllItems();
    
    for (Grupo g : GerenciadorDados.todosGrupos) {
        jcboxGrupos.addItem(g.getNome());
    }
}
    
    private Selecoes buscarSelecaoPorNome(String nome) {
    for (Selecoes s : GerenciadorDados.todasSelecoes) {
        // Substitua por getNome() ou o método que você usa para pegar o nome da seleção
        if (s.getNome().equalsIgnoreCase(nome)) { 
            return s;
        }
    }
    return null;
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jcboxGrupos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelaClassificacao = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jLabel2.setText("jLabel2");

        jTextField9.setText("jTextField9");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("x");

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("x");

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });

        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("x");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Confrontos");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jcboxGrupos.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jcboxGrupos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcboxGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxGruposActionPerformed(evt);
            }
        });

        jtabelaClassificacao.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jtabelaClassificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Equipe", "Pt's", "Pj", "Vit", "Em", "Der", "Gm", "Gc", "Sg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtabelaClassificacao);
        if (jtabelaClassificacao.getColumnModel().getColumnCount() > 0) {
            jtabelaClassificacao.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Selecione grupo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(465, 465, 465)
                    .addComponent(jbSalvar))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(481, 481, 481)
                    .addComponent(jLabel1)
                    .addGap(233, 233, 233)))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcboxGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboxGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jbSalvar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        try {
        // Varre todas as linhas da tabela que estão aparecendo na tela
        for (int i = 0; i < modeloTabela.getRowCount(); i++) {
            String nomeSelecao = (String) modeloTabela.getValueAt(i, 0);
            
            // Pega o que o usuário digitou em cada coluna e converte para número inteiro
            int pts = Integer.parseInt(modeloTabela.getValueAt(i, 1).toString());
            int pj  = Integer.parseInt(modeloTabela.getValueAt(i, 2).toString());
            int vit = Integer.parseInt(modeloTabela.getValueAt(i, 3).toString());
            int e   = Integer.parseInt(modeloTabela.getValueAt(i, 4).toString());
            int der = Integer.parseInt(modeloTabela.getValueAt(i, 5).toString());
            int gm  = Integer.parseInt(modeloTabela.getValueAt(i, 6).toString());
            int gc  = Integer.parseInt(modeloTabela.getValueAt(i, 7).toString());
            int sg  = Integer.parseInt(modeloTabela.getValueAt(i, 8).toString());
            
            // Localiza a seleção na memória do sistema e atualiza seus dados
            Selecoes sel = buscarSelecaoPorNome(nomeSelecao);
            if (sel != null) {
                sel.setPontos(pts);
                sel.setPartidasJogadas(pj);
                sel.setVitorias(vit);
                sel.setEmpates(e);
                sel.setDerrotas(der);
                sel.setGolsMarcados(gm);
                sel.setGolContra(gc);
                sel.setSaldoGols(sg);
            }
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Classificação do grupo salva com sucesso!");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar. Certifique-se de digitar apenas números nas tabelas.");
    }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jcboxGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxGruposActionPerformed
                                               
    int indexSelecionado = jcboxGrupos.getSelectedIndex();
    
    if (indexSelecionado != -1) {
        Grupo grupoAtual = GerenciadorDados.todosGrupos.get(indexSelecionado);
        modeloTabela.setRowCount(0); // Limpa a tabela antes de carregar
        
        for (String nomeSelecao : grupoAtual.getSelecoes()) {
            // Busca o objeto completo da seleção para pegar os dados reais do campeonato
            Selecoes sel = buscarSelecaoPorNome(nomeSelecao);
            
            if (sel != null) {
                // Adiciona a linha com os dados REAIS armazenados na seleção
                modeloTabela.addRow(new Object[]{
                    sel.getNome(), 
                    sel.getPontos(), 
                    sel.getPartidasJogadas(), 
                    sel.getVitorias(), 
                    sel.getEmpates(), 
                    sel.getDerrotas(), 
                    sel.getGolsMarcados(), 
                    sel.getGolContra(), 
                    sel.getSaldoGols()
                });
            } else {
                // Caso de segurança (se não achar o objeto, põe zerado)
                modeloTabela.addRow(new Object[]{nomeSelecao, 0, 0, 0, 0, 0, 0, 0, 0});
            }
        }
    }

    }//GEN-LAST:event_jcboxGruposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new INConfronto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcboxGrupos;
    private javax.swing.JTable jtabelaClassificacao;
    // End of variables declaration//GEN-END:variables
}
