
import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class INSelecoes extends javax.swing.JFrame {

    // Lista na memória para guardar os jogadores desta seleção antes de salvar tudo
    private ArrayList<Jogador> jogadoresTemporarios = new ArrayList<>();

    // O "motor" que gerencia os itens visíveis dentro do seu JList
    private DefaultListModel<String> modeloLista = new DefaultListModel<>();

    /**
     * Creates new form Selecao
     */
    public INSelecoes() {
        initComponents();

        setSize(400, 300);
        setLocationRelativeTo(null);
        setVisible(true);
        jListJogadores.setModel(modeloLista);  //Vincula o motor de renderização ao componente da tela

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jtfNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtfCuriosidade = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfParticipacoes = new javax.swing.JTextField();
        jtfNomeDaSelecao = new javax.swing.JTextField();
        jtfMelhorColocacao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListJogadores = new javax.swing.JList<>();
        jBtnAdd = new javax.swing.JButton();
        jBtnRmv = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        JcheckEstreante = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1086, 565));

        jtfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Titulos:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Jogadores:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Curiosidade Sobre o Pais:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Estreante em Copas:");

        jtfCuriosidade.setColumns(20);
        jtfCuriosidade.setRows(5);
        jScrollPane3.setViewportView(jtfCuriosidade);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Participações:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setText("Seleção");

        jtfNomeDaSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeDaSelecaoActionPerformed(evt);
            }
        });

        jtfMelhorColocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMelhorColocacaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nome da Seleção:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Melhor Colocação:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Numero:");

        jScrollPane1.setViewportView(jListJogadores);

        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnRmv.setText("-");
        jBtnRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRmvActionPerformed(evt);
            }
        });

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSalvarMouseClicked(evt);
            }
        });
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        JcheckEstreante.setText("Sim");
        JcheckEstreante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcheckEstreanteActionPerformed(evt);
            }
        });

        jButton1.setText("Próximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNomeDaSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jtfMelhorColocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfNumero))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfParticipacoes))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnAdd)
                                    .addComponent(jBtnRmv))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(JcheckEstreante)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(329, 329, 329)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnSalvar)
                                .addGap(56, 56, 56)
                                .addComponent(jButton1)
                                .addGap(368, 368, 368)))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(513, 513, 513))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeDaSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMelhorColocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfParticipacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnAdd)
                            .addComponent(JcheckEstreante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnRmv)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSalvar)
                            .addComponent(jButton1))
                        .addGap(137, 137, 137))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroActionPerformed

    private void jtfNomeDaSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeDaSelecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeDaSelecaoActionPerformed

    private void jtfMelhorColocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMelhorColocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMelhorColocacaoActionPerformed

    private void JcheckEstreanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcheckEstreanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcheckEstreanteActionPerformed

    private void jBtnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalvarMouseClicked

    }//GEN-LAST:event_jBtnSalvarMouseClicked

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:

        INJogador iNJogador = new INJogador(this);
        iNJogador.setVisible(true);

    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRmvActionPerformed
        // TODO add your handling code here:

        // Pega a linha que o usuário clicou no JList (-1 significa que ele não clicou em nada)
        int indiceSelecionado = jListJogadores.getSelectedIndex();

        if (indiceSelecionado != -1) {
            // Remove da lista de memória usando o índice
            jogadoresTemporarios.remove(indiceSelecionado);

            // Atualiza a tela para sumir com o jogador deletado
            atualizarListaVisual();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um jogador na lista para poder remover!");
        }
    }//GEN-LAST:event_jBtnRmvActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            String nome = jtfNomeDaSelecao.getText();
            String melhorColocacao = jtfMelhorColocacao.getText();
            String curiosidade = jtfCuriosidade.getText();
            int titulos = Integer.parseInt(jtfTitulo.getText());
            int participacoes = Integer.parseInt(jtfParticipacoes.getText());
            boolean estreante = JcheckEstreante.isSelected();

            // 1. Cria a seleção (Ajuste os parâmetros se o construtor da sua classe Selecoes for diferente)
            Selecoes novaSelecao = new Selecoes(
                    1, // Substitui WIDTH por um ID padrão (ex: 1)
                    nome,
                    titulos,
                    estreante,
                    participacoes,
                    melhorColocacao,
                    curiosidade,
                    jogadoresTemporarios,
                    0, 0, 0, 0, 0, 0, 0, 0 // 🌟 Todos os 8 dados do campeonato começam estritamente em 0!
            );

            // 2. SALVA DE VERDADE NO SEU SISTEMA GLOBAL
            GerenciadorDados.todasSelecoes.add(novaSelecao);

            // 3. Avisa o usuário que deu certo
            javax.swing.JOptionPane.showMessageDialog(this, "Seleção '" + nome + "' salva com sucesso!");

            // 4. Limpa a tela para cadastrar a próxima!
            limparCampos();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha os campos de títulos e participações com números válidos.");
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Abre a tela de Grupos que configuramos antes
        INGrupo telaGrupo = new INGrupo();
        telaGrupo.setVisible(true);
        telaGrupo.setLocationRelativeTo(null);

        // Fecha a tela de seleções atual para avançar no fluxo
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
    private void limparCampos() {
        jtfNomeDaSelecao.setText("");
        jtfMelhorColocacao.setText("");
        jtfCuriosidade.setText("");
        jtfTitulo.setText("");
        jtfParticipacoes.setText("");
        jtfNumero.setText("");
        JcheckEstreante.setSelected(false);

        // Limpa os jogadores salvos na memória e limpa o JList da tela
        jogadoresTemporarios.clear();
        modeloLista.clear();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GerenciadorDados.carregarDadosPredefinidos();

        /* Código padrão do NetBeans que abre a tela... */
        java.awt.EventQueue.invokeLater(() -> {
            new INSelecoes().setVisible(true); // Ou o nome da sua tela inicial
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JcheckEstreante;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnRmv;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListJogadores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jtfCuriosidade;
    private javax.swing.JTextField jtfMelhorColocacao;
    private javax.swing.JTextField jtfNomeDaSelecao;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfParticipacoes;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables

    // Método público para que a INJogador possa chamar
    public void adicionarJogadorNaLista(Jogador novo) {
        // 1. Adiciona na nossa lista real (memória)
        jogadoresTemporarios.add(novo);

        // 2. Atualiza a lista visual (tela)
        atualizarListaVisual();
    }

    // Método auxiliar para redesenhar o JList sempre que houver mudanças
    private void atualizarListaVisual() {
        modeloLista.clear(); // Limpa o que estava na tela

        // Percorre a lista de memória e joga os nomes no modelo visual
        for (Jogador j : jogadoresTemporarios) {
            modeloLista.addElement(j.getNome() + " (" + j.getPosicao() + ")");
        }
    }
}
